const { EmpresaSchema, Empresa } = require('./empresa.model');
const { MovimientoSchema, Movimiento } = require('./movimiento.model');
const { MenuSchema, Menu } = require('./menu.model');
const { RolUsuarioSchema, RolUsuario } = require('./rolUsuario.model');
const { MenuRolSchema, MenuRol } = require('./menuRol.model');
const { UsuarioSchema, Usuario } = require('./usuario.model');
const { HistorialSchema, Historial } = require('./historial.model');
const { MarcaSchema, Marca } = require('./marca.model');
const { CategoriaSchema, Categoria } = require('./categoria.model');
const { ProductoSchema, Producto } = require('./producto.model');
const { InventarioSchema, Inventario } = require('./inventario.model');
const { ProveedorSchema, Proveedor } = require('./proveedor.model');
const { ClienteSchema, Cliente } = require('./cliente.model');
const { FormaPagoSchema, FormaPago } = require('./formaPago.model');
const { CajaSchema, Caja } = require('./caja.model');
const { FacturaCompraSchema, FacturaCompra } = require('./facturaCompra.model');
const { CompraSchema, Compra } = require('./compra.model');
const { ImpuestoSchema, Impuesto } = require('./impuesto.model');
const { FacturaVentaSchema, FacturaVenta } = require('./facturaVenta.model');
const { VentaSchema, Venta } = require('./venta.model');
const { ImpuestoFacturaSchema,ImpuestoFactura} = require('./impuestoFactura.model');
const { AbonoFacturaVentaSchema, AbonoFacturaVenta } = require('./AbonoFacturaVenta.model');

function setupModels(sequelize) {
  Empresa.init(EmpresaSchema, Empresa.config(sequelize));
  Movimiento.init(MovimientoSchema, Movimiento.config(sequelize));
  Menu.init(MenuSchema, Menu.config(sequelize));
  RolUsuario.init(RolUsuarioSchema, RolUsuario.config(sequelize));
  MenuRol.init(MenuRolSchema, MenuRol.config(sequelize));
  Usuario.init(UsuarioSchema, Usuario.config(sequelize));
  Historial.init(HistorialSchema, Historial.config(sequelize));
  Marca.init(MarcaSchema, Marca.config(sequelize));
  Categoria.init(CategoriaSchema, Categoria.config(sequelize));
  Producto.init(ProductoSchema, Producto.config(sequelize));
  Inventario.init(InventarioSchema, Inventario.config(sequelize));
  Proveedor.init(ProveedorSchema, Proveedor.config(sequelize));
  Cliente.init(ClienteSchema, Cliente.config(sequelize));
  FormaPago.init(FormaPagoSchema, FormaPago.config(sequelize));
  Caja.init(CajaSchema, Caja.config(sequelize));
  FacturaCompra.init(FacturaCompraSchema, FacturaCompra.config(sequelize));
  Compra.init(CompraSchema, Compra.config(sequelize));
  Impuesto.init(ImpuestoSchema, Impuesto.config(sequelize));
  FacturaVenta.init(FacturaVentaSchema, FacturaVenta.config(sequelize));
  Venta.init(VentaSchema, Venta.config(sequelize));
  ImpuestoFactura.init(ImpuestoFacturaSchema,ImpuestoFactura.config(sequelize));
  AbonoFacturaVenta.init(AbonoFacturaVentaSchema, AbonoFacturaVenta.config(sequelize));

  Usuario.associate(sequelize.models);
  RolUsuario.associate(sequelize.models);
  Historial.associate(sequelize.models);
  Menu.associate(sequelize.models);
  MenuRol.associate(sequelize.models);
  Marca.associate(sequelize.models);
  Producto.associate(sequelize.models);
  Categoria.associate(sequelize.models);
  Inventario.associate(sequelize.models);
  Venta.associate(sequelize.models);
  Compra.associate(sequelize.models);
  FormaPago.associate(sequelize.models);
  FacturaCompra.associate(sequelize.models);
  FacturaVenta.associate(sequelize.models);
  Proveedor.associate(sequelize.models);
  Cliente.associate(sequelize.models);
  Caja.associate(sequelize.models);
  AbonoFacturaVenta.associate(sequelize.models);
  ImpuestoFactura.associate(sequelize.models);
  Impuesto.associate(sequelize.models);
}

module.exports = setupModels;
